"""Pagos: sync_hash y origen

Revision ID: 05725679a0fe
Revises: 3ebb2cf244f2
Create Date: 2026-10-08 01:23:36.215861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05725679a0fe'
down_revision = '3ebb2cf244f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_accion')
        batch_op.drop_index('ix_audit_fecha')
        batch_op.drop_index('ix_audit_user')
        batch_op.create_index(batch_op.f('ix_audit_log_fecha'), ['fecha'], unique=False)

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facturas_precio_manual'), ['precio_manual'], unique=False)

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('origen', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_pagos_origen'), ['origen'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_sync_estado'), ['sync_estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_sync_hash'), ['sync_hash'], unique=False)
        batch_op.drop_column('recargo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recargo', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_pagos_sync_hash'))
        batch_op.drop_index(batch_op.f('ix_pagos_sync_estado'))
        batch_op.drop_index(batch_op.f('ix_pagos_origen'))
        batch_op.drop_column('origen')
        batch_op.drop_column('sync_hash')

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facturas_precio_manual'))

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_fecha'))
        batch_op.create_index('ix_audit_user', ['user_id'], unique=False)
        batch_op.create_index('ix_audit_fecha', ['fecha'], unique=False)
        batch_op.create_index('ix_audit_accion', ['accion'], unique=False)

    # ### end Alembic commands ###
