"""Esquema inicial El Michin

Revision ID: 3ebb2cf244f2
Revises: 
Create Date: 2026-09-30 23:33:26.167514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ebb2cf244f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('codigo_barras', sa.String(length=50), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_codigo_barras'), ['codigo_barras'], unique=True)
        batch_op.create_index(batch_op.f('ix_productos_nombre'), ['nombre'], unique=True)

    op.create_table('tiendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creada_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('borradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('carrito_json', sa.Text(), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=200), nullable=True),
    sa.Column('cliente_documento', sa.String(length=50), nullable=True),
    sa.Column('cliente_direccion', sa.String(length=200), nullable=True),
    sa.Column('cliente_telefono', sa.String(length=50), nullable=True),
    sa.Column('cliente_email', sa.String(length=100), nullable=True),
    sa.Column('metodo_pago', sa.String(length=20), nullable=True),
    sa.Column('bolsa_cantidad', sa.Integer(), nullable=True),
    sa.Column('fecha_guardado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('documento', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('saldo_actual', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('sync_estado', sa.String(length=20), nullable=True),
    sa.Column('sync_fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tienda_id', 'documento', name='uq_cliente_tienda_doc')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_tienda_id'), ['tienda_id'], unique=False)

    op.create_table('configuracion',
    sa.Column('tienda_id', sa.Integer(), nullable=True),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('tienda_id', 'clave')
    )
    op.create_table('producto_tienda',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_proveedor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('precio_proveedor2', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('precio_proveedor3', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('porcentaje', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('precio_venta', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('descuento1_porcentaje', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('precio_venta1', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('descuento2_porcentaje', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('precio_venta2', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('descuento3_porcentaje', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('precio_venta3', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('condicion1', sa.String(length=10), nullable=True),
    sa.Column('condicion2', sa.String(length=10), nullable=True),
    sa.Column('condicion3', sa.String(length=10), nullable=True),
    sa.Column('sync_estado', sa.String(length=20), nullable=True),
    sa.Column('sync_fecha', sa.DateTime(), nullable=True),
    sa.Column('sync_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('producto_id', 'tienda_id')
    )
    with op.batch_alter_table('producto_tienda', schema=None) as batch_op:
        batch_op.create_index('idx_prod_tienda_stock', ['tienda_id', 'cantidad'], unique=False)
        batch_op.create_index(batch_op.f('ix_producto_tienda_sync_estado'), ['sync_estado'], unique=False)

    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('tabla', sa.String(length=50), nullable=True),
    sa.Column('registros', sa.Integer(), nullable=True),
    sa.Column('exitoso', sa.Boolean(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_log_fecha'), ['fecha'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sync_estado', sa.String(length=20), nullable=True),
    sa.Column('sync_fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ventas_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_tienda_id'), ['tienda_id'], unique=False)

    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=20), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=20), nullable=True),
    sa.Column('recargo_nequi', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('recargo_bolsa', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_pagado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vueltas', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tipo_pago', sa.String(length=20), nullable=True),
    sa.Column('estado_credito', sa.String(length=20), nullable=True),
    sa.Column('saldo_pendiente', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('sync_estado', sa.String(length=20), nullable=True),
    sa.Column('sync_fecha', sa.DateTime(), nullable=True),
    sa.Column('sync_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tienda_id', 'numero_factura', name='uq_factura_tienda_num')
    )
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.create_index('idx_facturas_tienda_fecha', ['tienda_id', 'fecha_hora'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_fecha_hora'), ['fecha_hora'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_sync_estado'), ['sync_estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_tienda_id'), ['tienda_id'], unique=False)

    op.create_table('detalle_factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('producto_nombre', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detalle_factura', schema=None) as batch_op:
        batch_op.create_index('idx_detalle_factura', ['factura_id'], unique=False)
        batch_op.create_index('idx_detalle_producto', ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detalle_factura_factura_id'), ['factura_id'], unique=False)

    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=20), nullable=True),
    sa.Column('sync_estado', sa.String(length=20), nullable=True),
    sa.Column('sync_fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_factura_id'), ['factura_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_factura_id'))

    op.drop_table('pagos')
    with op.batch_alter_table('detalle_factura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detalle_factura_factura_id'))
        batch_op.drop_index('idx_detalle_producto')
        batch_op.drop_index('idx_detalle_factura')

    op.drop_table('detalle_factura')
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facturas_tienda_id'))
        batch_op.drop_index(batch_op.f('ix_facturas_sync_estado'))
        batch_op.drop_index(batch_op.f('ix_facturas_fecha_hora'))
        batch_op.drop_index('idx_facturas_tienda_fecha')

    op.drop_table('facturas')
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ventas_tienda_id'))
        batch_op.drop_index(batch_op.f('ix_ventas_fecha'))

    op.drop_table('ventas')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))

    op.drop_table('usuarios')
    with op.batch_alter_table('sync_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_log_fecha'))

    op.drop_table('sync_log')
    with op.batch_alter_table('producto_tienda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_producto_tienda_sync_estado'))
        batch_op.drop_index('idx_prod_tienda_stock')

    op.drop_table('producto_tienda')
    op.drop_table('configuracion')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_tienda_id'))
        batch_op.drop_index(batch_op.f('ix_clientes_nombre'))

    op.drop_table('clientes')
    op.drop_table('borradores')
    op.drop_table('tiendas')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_nombre'))
        batch_op.drop_index(batch_op.f('ix_productos_codigo_barras'))

    op.drop_table('productos')
    # ### end Alembic commands ###
