"""Configuracion: sync_estado y sync_fecha

Revision ID: e2e903e57d88
Revises: 05725679a0fe
Create Date: 2026-10-08 15:57:19.189167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e903e57d88'
down_revision = '05725679a0fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_estado', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sync_fecha', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_configuracion_sync_estado'), ['sync_estado'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracion_sync_estado'))
        batch_op.drop_column('sync_fecha')
        batch_op.drop_column('sync_estado')

    # ### end Alembic commands ###
